productly/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.inicio, name="inicio"),
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls'))
]

productos/urls.py
""" productos/urls """
from django.urls import path
from . import views
app_name = 'productos'
urlpatterns = [
    path('', views.index, name='index'),
    path('formulario', views.formulario, name='formulario'),
    path(
        '<int:producto_id>',
        views.detalle,
        name='detalle'
    )
]

productos/models.py
from django.db import models
from django.utils import timezone
# Create your models here.


class Categoria(models.Model):
    """Modelo categoria"""
    nombre = models.CharField(max_length=255)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    """Modelo productos"""

    nombre = models.CharField(max_length=255)
    stock = models.IntegerField()
    puntaje = models.FloatField()
    categoria = models.ForeignKey(
        Categoria, default=1, on_delete=models.CASCADE)

    creado_en = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.nombre

productos/forms.py
from . import models
from django.forms import ModelForm


class ProductoForm(ModelForm):
    class Meta:
        model = models.Producto
        fields = ['nombre', 'stock', 'puntaje', 'categoria']

productly/views.py
from django.shortcuts import render


def inicio(request):
    return render(
        request,
        'inicio.html'
    )

productos/views.py
from django.http import Http404, HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render, get_object_or_404

from .forms import ProductoForm
from .models import Producto
# Create your views here.

# /productos/


def index(request):
    productos = Producto.objects.all()
    return render(
        request,
        'index.html',
        context={'productos': productos}
    )


def detalle(request, producto_id):
    producto = get_object_or_404(Producto, id=producto_id)
    producto = Producto.objects.get(id=producto_id)

    return render(
        request,
        'detalle.html',
        context={'producto': producto}
    )


def formulario(request):
    if request.method == 'POST':
        form = ProductoForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/productos')
    else:
        form = ProductoForm()
    return render(
        request,
        'producto_form.html',
        context={'form': form}
    )

productos/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    {% block content %}

    {% endblock %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

productos/templates/detalle.html
{%extends 'base.html'%}

{%block content%}
<div>
    <h6>{{producto.nombre}}</h6>
    <p>{{producto.categoria}}</p>
    <p>{{producto.stock}}</p>
    <p>{{producto.puntaje}}</p>
    <p>{{producto.creado_en}}</p>
</div>
{%endblock%}

productos/templates/index.html
{%extends 'base.html'%}

{% block content %}
<h1>Productos</h1>
<a href="{% url 'productos:formulario' %}">Nuevo Producto</a>

<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Stock</th>
            <th>Puntaje</th>
            <th>Categoria</th>
        </tr>
    </thead>
    <tbody>
        {%for producto in productos%}
        <tr>
            <td>
                <a href="{% url 'productos:detalle' producto.id %}">
                    {{producto.nombre}}
                </a>
            </td>
            <td>
                {{producto.stock}}
            </td>
            <td>
                {{producto.puntaje}}
            </td>
            <td>
                {{producto.categoria}}
            </td>
        </tr>
        {%endfor%}
    </tbody>
</table>
{% endblock %}

productos/templates/producto_form.html
{%extends 'base.html'%}

{% block content %}
<form 
    novalidate
    action = "{% url 'productos:formulario' %}" 
    method = 'post'>
    {% csrf_token %}
    {{ form }}
    <button type="submit" value="Enviar">Enviar</button> 
</form>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Productly</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
</head>

<body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'inicio' %}">Inicio</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'productos:index' %}">Productos</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
        {% block content %}

        {% endblock %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm"
        crossorigin="anonymous"></script>
</body>

</html>

templates/django/forms/label.html
{% if use_tag %}<{{ tag }}{% include 'django/forms/attrs.html' %} class="form-label" >{{ label }}</{{ tag }}>{% else %}{{ label }}{% endif %}

templates/django/forms/widgets/input.html
<input 
    class="form-control {{widget.attrs.class}}"
    type="{{ widget.type }}" 
    name="{{ widget.name }}"
    {% if widget.value != None %} 
        value="{{ widget.value|stringformat:'s' }}"
    {% endif %}
    {% include "django/forms/widgets/attrs.html" %}>

templates/django/forms/widgets/select.html
<select class="form-select" name="{{ widget.name }}"{% include "django/forms/widgets/attrs.html" %}>{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
    <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
    {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
    </optgroup>{% endif %}{% endfor %}
</select>

templates/form_snippet.html
{% load add_attr %}

{%for field in form%}
<div class="mb-3">
    {{ field.label_tag }} 
    {% if field.errors %}
        {{ field|add_attr:"class:is-invalid" }}
    {% else %}
        {{ field }}
    {% endif %}
    <div id="validationServer03Feedback" class="invalid-feedback">
    {% for error in field.errors %}
        {{error}}
    {% endfor %}  
    </div>
</div>  
{% endfor %}

templates/inicio.html
{%extends 'base.html' %}

{% block content %}
    Hola mundo! Bienvenidos a productly v1.1
{% endblock content %}